root_dir: "."
data_dir: "{{ root_dir }}/data"
external_data_dir: "{{ data_dir }}/external"
log_dir: "{{ root_dir }}/logs"
tests_dir: "{{ root_dir }}/tests"
db_name: 'ParquetDB'
use_multiprocessing: False
serialize_python_objects: True

numpy_config:
  np_printoptions:
    linewidth:  400
    precision: 3

parquetdb_config:
  normalize_kwargs:
    load_kwargs:
      batch_readahead: 16
      fragment_readahead: 4
      batch_size: 131072
    use_threads: True
    max_partitions: 1024
    max_open_files: 1024
    max_rows_per_file: 10000000
    min_rows_per_group: 50000
    max_rows_per_group: 100000
    existing_data_behavior: overwrite_or_ignore
    create_dir: True
  load_kwargs:
    batch_readahead: 16
    fragment_readahead: 4
    batch_size: 131072
  
    
