root_dir: "."
data_dir: "{{ root_dir }}/data"
external_data_dir: "{{ data_dir }}/external"
log_dir: "{{ root_dir }}/logs"
tests_dir: "{{ root_dir }}/tests"

numpy_config:
  np_printoptions:
    linewidth:  400
    precision: 3

    
